server {
    listen 443 ssl;
    server_name domain.ru www.domain.ru;
    ssl_certificate /etc/letsencrypt/live/worktime-sync.ru/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/worktime-sync.ru/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        proxy_pass ip-addr;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name domain.ru www.domain.ru;
    return 301 https://$host$request_uri;
}
